config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :courses
  resources :users, only: [:index]
  get 'home/index'
  root 'home#index'
  #root 'static_pages#landing_page' 
  get 'static_pages/landing_page'
  # get 'static_pages/privacy_policy'
  get 'privacy_policy', to: "static_pages#privacy_policy"


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  validates :title, :short_description, :language, :price, :level, presence: true
  validates :description, presence: true, length: {minimum: 5}

  belongs_to :user
  def to_s
    title
  end

  has_rich_text :description

  extend FriendlyId
  friendly_id :title, use: :slugged

  LANGUAGES = [:"English", :"Russian", :"Polish", :"Hindi", :"Kazakh", :"French"]
  def self.languages
    LANGUAGES.map {|language| [language, language]}
  end

  LEVELS = [:"Beginner", :"Intermediate", :"Advanced"]
  def self.levels
    LEVELS.map {|level| [level, level]}
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :confirmable
  
  has_many :courses

  def to_s
    email
  end

  def username
    self.email.split(/@/).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]

  # GET /courses or /courses.json
  def index
    if params[:title]
      @courses = Course.where('title ILIKE ?', "%#{params[:title]}%") #case-insensitive
    else
      #@courses = Course.all
      @query = Course.ransack(params[:q])
      @courses = @query.result.includes(:user)
    end
  end

  # GET /courses/1 or /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)
    @course.user = current_user
    
    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:title, 
                      :description,
                      :short_description,
                      :price,
                      :language,
                      :level)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index]

  def index
    @courses = Course.all.limit(3)
    @latest_courses = Course.all.limit(3).order(created_at: :desc)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def landing_page
  end

  def privacy_policy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    #@users = User.all.order(created_at: :desc)

    @query = User.ransack(params[:q])
    @users = @query.result(distinct: true)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/courses/_course.html.haml
.col-sm-4
  .card.m-2
    .card-header 
      .fa.fa-graduation-cap
      = link_to course.title, course_path(course)
    .card-body
      = course.description
      %small= simple_format(course.short_description)
    .card-footer
      .text-center
        = number_to_currency(course.price)
      
    .card-footer
      .row
        .col-md-6
          .fa.fa-globe-africa
          = course.language
        .col-md-6
          .text-right
            .fa.fa-signal
            = course.level
      
    .card-footer
      .row 
        .col-md-6
          .far.fa-clock
          = course.created_at.strftime('%d-%b-%Y')
        .col-md-6 
          .text-right
            .fa.fa-chalkboard-teacher
            = course.user.username
    .card-footer
      = link_to 'Show', course, class: 'btn btn-sm btn-primary'
      = link_to 'Edit', edit_course_path(course), class: 'btn btn-sm btn-warning'
      = link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger'

app/views/courses/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@course) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
    = f.label :description
    = f.rich_text_area :description
    %small= f.error :description, class: 'text-danger'
    = f.input :short_description
    /= f.input :language, collection: [ "English", "Polish", "Russian"]
    = f.input :language, collection: Course.languages, include_blank: true

    /= f.input :level, collection: [ "Beginner", "Intermediate", "Advanced"]
    = f.input :level, collection: Course.levels, include_blank: true
    = f.input :price

  .form-actions
    = f.button :submit

app/views/courses/edit.html.haml
.card
  .card-header 
    %h1 Editing course
  .card-body
    = render 'form'


= link_to 'Show', @course
\|
= link_to 'Back', courses_path

app/views/courses/index.html.haml
%h1 
  Courses:
  = @courses.count

.row 
  .col-md-2 
    = search_form_for @query do |f|
      = f.label :title
      = f.search_field :title_cont, placeholder: 'Title', class: 'form-control form-control-sm'
      = f.label :description
      = f.search_field :short_description_cont, placeholder: 'Description', class: 'form-control form-control-sm'
      = f.label :language
      = f.select :language_cont, Course.languages, include_blank: true, class: 'form-control form-control-sm'

      = f.label :level
      = f.select :level_cont, Course.levels, include_blank: true, class: 'form-control form-control-sm'

      = f.label :price
      = f.search_field :price_eq, placeholder: 'Price', class: 'form-control form-control-sm'
      = f.label :teacher
      = f.search_field :user_email_cont, placeholder: 'Email', class: 'form-control form-control-sm'
      = f.submit
    = link_to 'refresh', courses_path

  .col-md-10
    .row
      - @courses.each do |course|
        = render 'courses/course', course: course

%br

= link_to 'New Course', new_course_path

app/views/courses/new.html.haml
.card
  .card-header 
    %h1 New course
  .card-body
    = render 'form'

= link_to 'Back', courses_path

app/views/courses/show.html.haml
= link_to 'Courses', courses_path
\/
= link_to @course.title, course_path(@course)

= render 'courses/course', course: @course

app/views/home/index.html.haml
%h1 
  Home#index

.p-5.mb-4.bg-dark.rounded-3.text-white
  .display-4
    What do you want to learn today?
  .p-4
  %form.form-inline.my-2.my-lg-0
    = form_tag(courses_path, method: :get) do
      .input-group
        = text_field_tag :title, params[:title], autocomplete: 'off', placeholder: "Search", class: 'form-control-sm'
        %span.input-group-append
          %button.btn.btn-primary.btn-sm{:type => "submit"}
            %span.fa.fa-search{"aria-hidden" => "true"}
.card-group 
  .card.card-body 
    %h1
      .fa.fa-graduation-cap 
    = Course.count
    online courses
    .row 
    Explore a variety of fresh topics 
  .card.card-body 
    %h1
      .fa.fa-chalkboard-teacher
    = Course.distinct.count(:user_id)
    expert instructors
    .row 
    Find the right instructor for you
  .card.card-body 
    %h1
      .fa.fa-user-graduate
    = User.count
    active learners 
    .row 
    Join the knowledge sharing community
  .card.card-body 
    %h1
      .fa.fa-infinity 
    Lifetime access
    .row 
    Learn on your schedule
  
%hr
%h2
  Popular courses
.row
  - @courses.each do |course|
    = render 'courses/course', course: course
%hr
%h2
  Top rated courses 
.row
  - @courses.each do |course|
    = render 'courses/course', course: course
%hr
%h2
  Latest courses 
.row
  - @latest_courses.each do |course|
    = render 'courses/course', course: course
%hr

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  = link_to root_path, class: 'navbar-brand' do
    E-Learn
  %a.navbar-brand{:href => "#"} E-Learn
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  
  #navbarSupportedContent.collapse.navbar-collapse
    - if current_user
      %ul.navbar-nav.mr-auto
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(root_path)}"}
          = link_to root_path, class: 'nav-link' do
            .fa.fa-home 
            Home
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(courses_path)}"}
          = link_to courses_path, class: 'nav-link' do
            .fa.fa-graduation-cap
            Courses 
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(new_course_path)}"}
          = link_to new_course_path, class: 'nav-link' do
            .fa.fa-plus
            New Course
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(users_path)}"}
          = link_to users_path, class: 'nav-link' do
            .fa.fa-users
            Users


      %form.form-inline.my-2.my-lg-0
        = form_tag(courses_path, method: :get) do
          .input-group
            = text_field_tag :title, params[:title], autocomplete: 'off', placeholder: "Search", class: 'form-control-sm'
            %span.input-group-append
              %button.btn.btn-primary.btn-sm{:type => "submit"}
                %span.fa.fa-search{"aria-hidden" => "true"}
      %ul.navbar-nav.mr-right
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(root_path)}"}
          = link_to root_path, class: 'nav-link' do
            .fa.fa-home
            Another link
        %li.nav-item.dropdown
          %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
            %b= current_user.email
          .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "navbarDropdown"}
            = link_to edit_user_registration_path, class: "dropdown-item" do
              .fa.fa-cog
              %b Account settings
            = link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do
              .fa.fa-sign-out-alt
              %b Sign out
    - else
      %ul.navbar-nav
        %li.nav-item= link_to 'Sign Up', new_user_registration_path, class: 'nav-link'
        %li.nav-item= link_to 'Log In', new_user_session_path, class: 'nav-link'

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", :role => "alert"}
      %button.btn-close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"}
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    %title Elearn
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    = render 'layouts/messages'
    .container
      %p
      = yield
    %br

app/views/static_pages/landing_page.html.haml
.container
  %h1
    %i.fas.fa-home
    Landing Page
  = link_to privacy_policy_path, class: "btn btn-lg btn-warning" do
    %i.fas.fa-file-word
    Privacy Policy

app/views/static_pages/privacy_policy.html.haml
%h1 
  StaticPages#privacy_policy
%p
  Find me in app/views/static_pages/privacy_policy.html.erb
  older path: static_pages_landing_page_path
= link_to "Home", root_path

app/views/users/_user.html.haml
.col-sm-4
  .card 
    .card-header 
      .fa.fa-user 
      = user.email 
    .card-footer 
      Signed up 
      = time_ago_in_words(user.created_at)
      ago 
    .card-footer
      .row 
      = 'sign_in_count'.humanize
      = user.sign_in_count
      .row 
      = 'current_sign_in_at'.humanize
      = user.current_sign_in_at
      .row 
      = 'last_sign_in_at'.humanize
      = user.last_sign_in_at
      .row 
      = 'current_sign_in_ip'.humanize
      = user.current_sign_in_ip
      .row 
      = 'last_sign_in_ip'.humanize
      = user.last_sign_in_ip
    .card-footer
      Confirmed email?
      - if user.confirmed_at.present?
        .badge.bg-success Yes
      - else
        .badge.bg-danger No

app/views/users/index.html.haml
.row 
  - @users.each do |user|
    = render 'users/user', user: user

.form-inline
  = search_form_for @query do |f|
    = f.search_field :email_cont, placeholder: 'email'
    = f.search_field :sign_in_count_eq, placeholder: 'sign in count'
    //= f.search_field :email_or_sign_in_count_eq, placeholder: 'email or sign in count'
    = f.submit
  .ml-2 
  = link_to 'refresh', users_path


%table.table.table-bordered
  %thead
    %tr 
      %th id
      %th= sort_link(@query, :email)
      %th created_at 
      %th= 'sign_in_count'.humanize 
      %th= 'current_sign_in_at'.humanize 
      %th= 'last_sign_in_at'.humanize 
      %th= 'current_sign_in_ip'.humanize 
      %th= 'last_sign_in_ip'.humanize 
  %tbody 
    - @users.each do |user|
      %tr 
        %td= user.id 
        %td= user.email 
        %td= user.created_at
        %td= user.sign_in_count
        %td= user.current_sign_in_at
        %td= user.last_sign_in_at
        %td= user.current_sign_in_ip
        %td= user.last_sign_in_ip